// bgphub — BGP route hub for redistributing routes to downstream BIRD2 peers.
//
// Reads a peer list from bgphub-peers.json, generates a BIRD2 config include
// file (bgphub-peers.conf) with an export filter and per-peer protocol blocks,
// and reloads BIRD2. Peers are managed via the bgphub CLI script on the VPS.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// ── Config ──────────────────────────────────────────────────────────────────

type BGPHubConfig struct {
	Enabled      bool
	WorkDir      string
	Nexthop      string   // sentinel IP for bgp_next_hop rewrite (e.g. 10.8.3.1)
	LocalAS      int      // AS number for the hub side of each peer session
	ExportProtos []string // BIRD2 protocol names to re-export (e.g. bgp_feed, user_vpn)
}

func bgphubConfigFromEnv(workDir string) BGPHubConfig {
	enabled := os.Getenv("BGPHUB_ENABLED") == "true"
	localAS := envOrInt("BGPHUB_LOCAL_AS", 0)
	nexthop := envOr("BGPHUB_NEXTHOP", "10.8.3.1")

	protos := "bgp_feed,user_vpn"
	if v := os.Getenv("BGPHUB_EXPORT_PROTOS"); v != "" {
		protos = v
	}
	var exportProtos []string
	for _, p := range strings.Split(protos, ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			exportProtos = append(exportProtos, p)
		}
	}

	return BGPHubConfig{
		Enabled:      enabled,
		WorkDir:      workDir,
		Nexthop:      nexthop,
		LocalAS:      localAS,
		ExportProtos: exportProtos,
	}
}

// ── Peer type ───────────────────────────────────────────────────────────────

type BGPHubPeer struct {
	Name string `json:"name"`
	IP   string `json:"ip"`
	AS   int    `json:"as"`
}

type bgphubPeersFile struct {
	Peers []BGPHubPeer `json:"peers"`
}

// ── Free functions ──────────────────────────────────────────────────────────

func bgphubPeersPath(workDir string) string { return filepath.Join(workDir, "bgphub-peers.json") }
func bgphubConfPath(workDir string) string  { return filepath.Join(workDir, "bgphub-peers.conf") }

// LoadBGPHubPeers reads the peer list from bgphub-peers.json.
// Returns nil (not an error) if the file does not exist.
func LoadBGPHubPeers(workDir string) ([]BGPHubPeer, error) {
	data, err := os.ReadFile(bgphubPeersPath(workDir))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var f bgphubPeersFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("parse bgphub-peers.json: %w", err)
	}
	return f.Peers, nil
}

// sanitizeBIRDName converts a human-readable name into a valid BIRD2 protocol
// name: lowercase, only [a-z0-9_], prefixed with bgphub_, max 64 chars.
var reNonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func sanitizeBIRDName(name string) string {
	s := strings.ToLower(name)
	s = reNonAlnum.ReplaceAllString(s, "_")
	s = strings.Trim(s, "_")
	if s == "" {
		s = "peer"
	}
	proto := "bgphub_" + s
	if len(proto) > 64 {
		proto = proto[:64]
	}
	return proto
}

// GenerateBGPHubConf produces the BIRD2 config content for the bgphub include file.
func GenerateBGPHubConf(cfg BGPHubConfig, peers []BGPHubPeer) string {
	var sb strings.Builder
	sb.WriteString("# bgphub — auto-generated by bird-route-manager. Do not edit.\n")
	sb.WriteString("# Managed via the bgphub CLI: bgphub add|remove|list\n")

	if len(peers) == 0 {
		sb.WriteString("# No peers configured.\n")
		return sb.String()
	}

	// Export filter
	sb.WriteString("\nfilter bgphub_export {\n")
	for _, proto := range cfg.ExportProtos {
		fmt.Fprintf(&sb, "    if proto = %q then { bgp_next_hop = %s; accept; }\n", proto, cfg.Nexthop)
	}
	sb.WriteString("    reject;\n")
	sb.WriteString("}\n")

	// Peer protocol blocks (sorted by IP for stable output)
	sorted := make([]BGPHubPeer, len(peers))
	copy(sorted, peers)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].IP < sorted[j].IP })

	for _, p := range sorted {
		protoName := sanitizeBIRDName(p.Name)
		fmt.Fprintf(&sb, "\nprotocol bgp %s {\n", protoName)
		fmt.Fprintf(&sb, "    local as %d;\n", cfg.LocalAS)
		fmt.Fprintf(&sb, "    neighbor %s as %d;\n", p.IP, p.AS)
		sb.WriteString("    hold time 240;\n")
		sb.WriteString("    ipv4 {\n")
		sb.WriteString("        import none;\n")
		sb.WriteString("        export filter bgphub_export;\n")
		sb.WriteString("    };\n")
		sb.WriteString("}\n")
	}

	return sb.String()
}

// EnsureBGPHubConf generates bgphub-peers.conf from the current peer list.
// If birdConfigure is non-nil and peers exist, it is called after writing.
func EnsureBGPHubConf(cfg BGPHubConfig, birdConfigure func() error) error {
	peers, err := LoadBGPHubPeers(cfg.WorkDir)
	if err != nil {
		return fmt.Errorf("bgphub: load peers: %w", err)
	}

	content := GenerateBGPHubConf(cfg, peers)
	if err := atomicWrite(bgphubConfPath(cfg.WorkDir), content); err != nil {
		return fmt.Errorf("bgphub: write conf: %w", err)
	}

	log.Printf("bgphub: generated config for %d peer(s)", len(peers))

	// If we have peers and a birdConfigure callback, reload BIRD2.
	// On normal startup, the main Manager's LoadState() will also call
	// birdc configure. But if the Manager has no state (fresh install),
	// LoadState returns without reloading, so we do it ourselves.
	if len(peers) > 0 && birdConfigure != nil {
		if err := birdConfigure(); err != nil {
			return fmt.Errorf("bgphub: bird configure: %w", err)
		}
	}

	return nil
}

// ── CLI helpers ─────────────────────────────────────────────────────────────
// These are used by the bgphub CLI script (which calls the binary with a
// subcommand). They are not used by the main service.

// SaveBGPHubPeers writes the peer list to bgphub-peers.json.
func SaveBGPHubPeers(workDir string, peers []BGPHubPeer) error {
	f := bgphubPeersFile{Peers: peers}
	data, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return err
	}
	return atomicWrite(bgphubPeersPath(workDir), string(data)+"\n")
}

// AddBGPHubPeer adds a peer to the list, validating against the allowed subnet.
func AddBGPHubPeer(workDir string, name, ip string, as int, allowedSubnet *net.IPNet) ([]BGPHubPeer, error) {
	parsedIP := net.ParseIP(ip)
	if parsedIP == nil {
		return nil, fmt.Errorf("invalid IP address: %s", ip)
	}
	if allowedSubnet != nil && !allowedSubnet.Contains(parsedIP) {
		return nil, fmt.Errorf("IP %s not in allowed subnet %s", ip, allowedSubnet)
	}
	if as < 1 || as > 4294967294 {
		return nil, fmt.Errorf("invalid AS number: %d", as)
	}

	peers, err := LoadBGPHubPeers(workDir)
	if err != nil {
		return nil, err
	}

	// Check for duplicate IP
	for _, p := range peers {
		if p.IP == ip {
			return nil, fmt.Errorf("peer with IP %s already exists (name: %s)", ip, p.Name)
		}
	}

	// Validate name produces a unique BIRD protocol name
	newProto := sanitizeBIRDName(name)
	for _, p := range peers {
		if sanitizeBIRDName(p.Name) == newProto {
			return nil, fmt.Errorf("peer name %q conflicts with existing peer %q (both produce protocol name %s)", name, p.Name, newProto)
		}
	}

	peers = append(peers, BGPHubPeer{Name: name, IP: ip, AS: as})
	if err := SaveBGPHubPeers(workDir, peers); err != nil {
		return nil, err
	}
	return peers, nil
}

// RemoveBGPHubPeer removes a peer by IP.
func RemoveBGPHubPeer(workDir, ip string) ([]BGPHubPeer, error) {
	peers, err := LoadBGPHubPeers(workDir)
	if err != nil {
		return nil, err
	}

	found := false
	var remaining []BGPHubPeer
	for _, p := range peers {
		if p.IP == ip {
			found = true
			continue
		}
		remaining = append(remaining, p)
	}
	if !found {
		return nil, fmt.Errorf("no peer with IP %s", ip)
	}

	if err := SaveBGPHubPeers(workDir, remaining); err != nil {
		return nil, err
	}
	return remaining, nil
}
